root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /docs/jquery-bundle
        permanent: false

docs:
    pattern: /docs
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /docs/jquery-bundle
        permanent: false

highlight:
    resource: "@JQueryBundle/Resources/config/routing.yml"
    prefix:   /docs/jquery-bundle
